import { defineType, defineField } from "sanity";

export default defineType({
  name: "siteSettings",
  title: "サイト設定",
  type: "document",
  fieldsets: [
    { name: "branding", title: "ブランディング" },
    { name: "contact", title: "連絡先" },
    { name: "sectionHeadings", title: "セクション見出し（英文 + 日本語）" },
  ],
  fields: [
    defineField({
      name: "siteName",
      title: "サイト名",
      type: "string",
      fieldset: "branding",
    }),
    defineField({
      name: "logo",
      title: "ロゴ（メイン）",
      type: "image",
      fieldset: "branding",
    }),
    defineField({
      name: "logoFooter",
      title: "ロゴ（フッター用）",
      type: "image",
      fieldset: "branding",
    }),
    defineField({
      name: "ogImage",
      title: "OGP画像",
      type: "image",
      fieldset: "branding",
    }),
    defineField({
      name: "contactEmail",
      title: "問い合わせ先メールアドレス",
      type: "string",
      fieldset: "contact",
    }),
    defineField({
      name: "phone",
      title: "電話番号",
      type: "string",
      fieldset: "contact",
    }),
    defineField({
      name: "address",
      title: "住所",
      type: "text",
      fieldset: "contact",
    }),
    defineField({
      name: "socialLinks",
      title: "SNSリンク",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "platform", title: "プラットフォーム", type: "string" }),
            defineField({ name: "url", title: "URL", type: "url" }),
          ],
        },
      ],
    }),
    // Section Headings
    defineField({
      name: "headingAboutEn",
      title: "About セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "About",
    }),
    defineField({
      name: "headingAboutJa",
      title: "About セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Kitaoとは？",
    }),
    defineField({
      name: "headingPortfolioEn",
      title: "Portfolio セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Portfolio",
    }),
    defineField({
      name: "headingPortfolioJa",
      title: "Portfolio セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "実績レポート",
    }),
    defineField({
      name: "headingCatchEn",
      title: "Catch セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Heartfelt Hospitality",
    }),
    defineField({
      name: "headingFeaturesEn",
      title: "Features セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Features",
    }),
    defineField({
      name: "headingFeaturesJa",
      title: "Features セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "弊社の特長",
    }),
    defineField({
      name: "headingPricingEn",
      title: "Pricing セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Pricing",
    }),
    defineField({
      name: "headingPricingJa",
      title: "Pricing セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "料金プラン",
    }),
    defineField({
      name: "headingCoordinateEn",
      title: "Coordinate セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Coordinate",
    }),
    defineField({
      name: "headingCoordinateJa",
      title: "Coordinate セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "テーブルコーディネート",
    }),
    defineField({
      name: "headingVenueEn",
      title: "Venue セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Venue",
    }),
    defineField({
      name: "headingVenueJa",
      title: "Venue セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "レンタル会場",
    }),
    defineField({
      name: "headingFlowEn",
      title: "Flow セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Flow",
    }),
    defineField({
      name: "headingFlowJa",
      title: "Flow セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "ご利用の流れ",
    }),
    defineField({
      name: "headingTestimonialsEn",
      title: "Testimonials セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Testimonials",
    }),
    defineField({
      name: "headingTestimonialsJa",
      title: "Testimonials セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "お客様の声",
    }),
    defineField({
      name: "headingContactEn",
      title: "Contact セクション見出し（英文）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "Contact",
    }),
    defineField({
      name: "headingContactJa",
      title: "Contact セクション見出し（日本語）",
      type: "string",
      fieldset: "sectionHeadings",
      initialValue: "お問い合わせ",
    }),
  ],
});
